# Generated by Django 4.2 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('wind', models.FloatField()),
                ('seismic_zone', models.CharField(max_length=20)),
                ('zone_factor', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('temp_min', models.FloatField()),
            ],
        ),
    ]
